title: BioMonth - CSC supercomputing and data management for bioscientists

plugins:
  - jekyll-sitemap


collections:
  collections_dir: hands-on
  connecting:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      path: "_lectures"
    values:
      layout: "slides-csc"
  -
    scope:
      path: "handson/_connecting"
    values:
      layout: "default"
  -
    scope:
      path: "_exercises"
    values:
      layout: "default"
