title: BioMonth - CSC supercomputing and data management for bioscientists

plugins:
  - jekyll-sitemap


collections:
  hands-on:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      path: "_lectures"
    values:
      layout: "slides-csc"
  -
    scope:
      path: "_hands-on"
    values:
      i18n: "_hands-on"
      layout: "connecting"
  -
    scope:
      path: "_exercises"
    values:
      layout: "default"
